### PR TITLE
Fix access code table layout

### LINKED ISSUE #93: AccessCodes Table - Fix horizontal sizing
Horizontal scroll bar showing when access code table is inside a modal

image

Also there's no more (overflow) button at the end of each row, but I'm not sure if that's meant to be there yet.

image

### PR DESCRIPTION
**Pull request by mikewuu**
Fixes #93 

Was due to `width: 100%` on the header component. Good to remove as any layout should use `flex` to avoid width issues because we're not sure what the parent component would be.

### Note on `AccessCodeTableContent`

After #80 was merged, we lost the ability to preview `AccessCodeTable` in storybook because without a fake it was trying to make real api calls.

As a temporary workaround, I've refactored out `AccessCodeTableContent` which is the UI for `AccessCodeTable`, without the data-binding. I've also updated the story to use `AccessCodeTableContent` for now until the fake client is ready.

### CODE REVIEW

**Comment by mikewuu** [comment]
Oh it was locally! Didn't know the fake was in place.

File: src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+              <div>
+                <AccessCodeKeyIcon />
+              </div>
+            </TableCell>
+            <TableCell className='seam-name-cell'>
+              <Title>{code.name}</Title>
+              <CodeDetails accessCode={code} />
+            </TableCell>
+            <TableCell className='seam-action-cell'>
+              {/* <IconButton>
```
Comment (razor-x) [inline src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx:48]: Is this attached to an issue?

**Review by razor-x — APPROVED** [review]
Note this issue was created to track adding the hook back https://github.com/seamapi/react/issues/108

File: src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx (hunk 1 above)
Comment (mikewuu) [reply src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx:48]: Yep, will be required when either of these are being implemented:

https://github.com/seamapi/react/issues/107
https://github.com/seamapi/react/issues/30

Comment (razor-x) [reply src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx:48]: Ok, can we remove the comments then? You can paste the code snippet in the issues if they are still relevant at that time.

Comment (mikewuu) [reply src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx:48]: Damn, merged this a little early. I usually don't leave comments in case they're left dangling for eternity, but it's pretty safe to say this won't be missed -- those 2 features are required.

Do you want me to remove the comments in a separate PR?

Comment (razor-x) [reply src/lib/ui/AccessCodeTable/AccessCodeTableContent.tsx:48]: No worries. As long as they eventually disappear haha
